In [35]:
%load_ext autoreload
%autoreload 2
import numpy as np
import pandas as pd
import sys, glob, os, re
import eda
sys.path.append('../../../github/module/')
import utils

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
app = pd.read_csv('../data/application_train_test.csv')
utils.to_pickles(df=app, path='../data', fname='application_train_test')

0it [00:00, ?it/s]

shape: (356255, 125)

3it [00:02,  1.46it/s]

In [2]:
app = utils.read_pickles(path='../data/application_train_test*.p').set_index('SK_ID_CURR')

100%|██████████| 3/3 [00:01<00:00,  2.77it/s]

In [40]:
app['AMT_ANNUITY'][app['AMT_ANNUITY'].between(left=4000, right=10000)]

SK_ID_CURR
100004    6750.0
100016    5881.5
100022    7875.0
100034    9000.0
100052    9000.0
100058    6750.0
100076    9679.5
100088    6750.0
100094    5301.0
100095    6750.0
100113    6696.0
100119    9000.0
100126    9000.0
100127    5341.5
100129    6750.0
100134    9000.0
100152    9720.0
100154    9000.0
100182    6750.0
100195    9373.5
100202    6597.0
100215    8172.0
100216    6705.0
100234    9000.0
100249    4513.5
100250    6529.5
100258    9135.0
100272    9000.0
100282    6750.0
100285    9000.0
           ...
451033    6430.5
451391    6160.5
451422    5472.0
451762    9450.0
451817    7110.0
451840    6034.5
452069    6597.0
452158    9648.0
452249    9648.0
452690    7204.5
452741    5742.0
452788    6750.0
452861    7326.0
452882    6313.5
453214    9981.0
453220    8464.5
453514    7965.0
453959    5220.0
454418    6048.0
454476    6898.5
454554    8194.5
454778    7704.0
454835    8887.5
454878    4977.0
455021    4450.5
455184    9409.5
455436    7605.0
455798    7452.0
455907    9018.0
456169    7411.5
Name: AMT_ANNUITY, Length: 25771, dtype: float64

In [36]:
utils.start(sys.argv[0])
df = eda.df_info(app)
display(df)
utils.end(sys.argv[0])
df.to_csv('../data/eda_application_train_test.csv')

#==============================================================================
# START!!! /mnt/c/Users/gixo/go/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py    PID: 28285    time: 2018-09-02 12:32:24.941289
#==============================================================================

Shape: (356255, 124)
Categorical: CODE_GENDER
Categorical: EMERGENCYSTATE_MODE
Categorical: FLAG_OWN_CAR
Categorical: FLAG_OWN_REALTY
Categorical: FONDKAPREMONT_MODE
Categorical: HOUSETYPE_MODE
Categorical: NAME_CONTRACT_TYPE
Categorical: NAME_EDUCATION_TYPE
Categorical: NAME_FAMILY_STATUS
Categorical: NAME_HOUSING_TYPE
Categorical: NAME_INCOME_TYPE
Categorical: NAME_TYPE_SUITE
Categorical: OCCUPATION_TYPE
Categorical: ORGANIZATION_TYPE
Categorical: WALLSMATERIAL_MODE
Categorical: WEEKDAY_APPR_PROCESS_START

,DataType,#Nulls,#Uniques,#Inf,#-Inf,Min,Mean,Max,Std,25%,50%,75%,z 1.96 val,z -1.96 val,z 1.96 cnt,z -1.96 cnt,top10 val,top10 cnt,top10 ratio
AMT_ANNUITY,float64,36,14166,0,0,1615.500000,27425.560657,2.580255e+05,14732.808190,16731.000000,25078.50000,34960.500000,5.630186e+04,-1450.743395,14003,0,"[9000.0, 13500.0, 6750.0, 10125.0, 37800.0, 11...","[6450, 5556, 2404, 2052, 1612, 1508, 1454, 135...","[0.02, 0.02, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0, 0..."
AMT_CREDIT,float64,0,6480,0,0,45000.000000,587767.413753,4.050000e+06,398623.693715,270000.000000,500211.00000,797557.500000,1.369070e+06,-193535.025929,15406,0,"[450000.0, 675000.0, 225000.0, 180000.0, 27000...","[11827, 10303, 9998, 7757, 7733, 7081, 4575, 4...","[0.03, 0.03, 0.03, 0.02, 0.02, 0.02, 0.01, 0.0..."
AMT_GOODS_PRICE,float64,278,1291,0,0,40500.000000,528019.997800,4.050000e+06,366064.985656,234000.000000,450000.00000,675000.000000,1.245507e+06,-189467.374084,18719,0,"[450000.0, 225000.0, 675000.0, 900000.0, 27000...","[30711, 29732, 28434, 17404, 12653, 11111, 996...","[0.09, 0.08, 0.08, 0.05, 0.04, 0.03, 0.03, 0.0..."
AMT_INCOME_TOTAL,float64,0,2741,0,0,25650.000000,170116.059860,1.170000e+08,223506.819009,112500.000000,153000.00000,202500.000000,6.081894e+05,-267957.305397,1836,0,"[135000.0, 112500.0, 157500.0, 180000.0, 90000...","[41312, 35870, 30991, 28924, 25427, 24462, 193...","[0.12, 0.1, 0.09, 0.08, 0.07, 0.07, 0.05, 0.04..."
AMT_REQ_CREDIT_BUREAU_DAY,float64,47568,9,0,0,0.000000,0.006281,9.000000e+00,0.104250,0.000000,0.00000,0.000000,2.106115e-01,-0.198049,1559,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 9.0, 8.0]","[307128, 1355, 113, 45, 26, 9, 8, 2, 1]","[0.86, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
AMT_REQ_CREDIT_BUREAU_HOUR,float64,47568,5,0,0,0.000000,0.005808,4.000000e+00,0.079736,0.000000,0.00000,0.000000,1.620915e-01,-0.150475,1715,0,"[0.0, 1.0, 2.0, 3.0, 4.0]","[306972, 1648, 57, 9, 1]","[0.86, 0.0, 0.0, 0.0, 0.0]"
AMT_REQ_CREDIT_BUREAU_MON,float64,47568,24,0,0,0.000000,0.231697,2.700000e+01,0.855949,0.000000,0.00000,0.000000,1.909358e+00,-1.445963,10642,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 9.0, ...","[264574, 33471, 5409, 1995, 1077, 603, 344, 29...","[0.74, 0.09, 0.02, 0.01, 0.0, 0.0, 0.0, 0.0, 0..."
AMT_REQ_CREDIT_BUREAU_QRT,float64,47568,11,0,0,0.000000,0.304399,2.610000e+02,0.786915,0.000000,0.00000,0.000000,1.846753e+00,-1.237955,20276,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, ...","[238976, 49435, 17410, 2212, 533, 75, 29, 8, 7...","[0.67, 0.14, 0.05, 0.01, 0.0, 0.0, 0.0, 0.0, 0..."
AMT_REQ_CREDIT_BUREAU_WEEK,float64,47568,9,0,0,0.000000,0.029995,8.000000e+00,0.191374,0.000000,0.00000,0.000000,4.050872e-01,-0.345098,8652,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 6.0, 5.0, 8.0, 7.0]","[300035, 8321, 202, 58, 34, 20, 10, 5, 2]","[0.84, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
AMT_REQ_CREDIT_BUREAU_YEAR,float64,47568,25,0,0,0.000000,1.911564,2.500000e+01,1.865338,0.000000,1.00000,3.000000,5.567627e+00,-1.744499,16341,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, ...","[82640, 72616, 58681, 39822, 24459, 14128, 809...","[0.23, 0.2, 0.16, 0.11, 0.07, 0.04, 0.02, 0.01..."
APARTMENTS_AVG,float64,179948,2415,0,0,0.000000,0.118138,1.000000e+00,0.108954,0.057700,0.08800,0.148500,3.316872e-01,-0.095411,8565,0,"[0.0825, 0.0619, 0.0928, 0.0722, 0.0082, 0.016...","[7773, 7345, 5172, 4619, 3986, 3451, 3330, 325...","[0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
APARTMENTS_MEDI,float64,179948,1172,0,0,0.000000,0.118549,1.000000e+00,0.109824,0.058300,0.08740,0.149400,3.338035e-01,-0.096705,8626,0,"[0.0833, 0.0625, 0.0937, 0.0729, 0.0083, 0.104...","[8278, 7777, 5433, 4881, 4049, 3590, 3528, 351...","[0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.0..."
APARTMENTS_MODE,float64,179948,780,0,0,0.000000,0.114914,1.000000e+00,0.108745,0.052500,0.08400,0.146000,3.280551e-01,-0.098226,8567,0,"[0.084, 0.063, 0.0945, 0.0735, 0.0084, 0.0168,...","[8752, 8663, 5578, 5068, 4519, 3780, 3604, 358...","[0.02, 0.02, 0.02, 0.01, 0.01, 0.01, 0.01, 0.0..."
BASEMENTAREA_AVG,float64,207584,3869,0,0,0.000000,0.088673,1.000000e+00,0.082312,0.044500,0.07650,0.112300,2.500050e-01,-0.072660,5554,0,"[0.0, 0.1091, 0.0545, 0.0727, 0.0818, 0.08, 0....","[16986, 305, 296, 295, 292, 274, 272, 268, 262...","[0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
BASEMENTAREA_MEDI,float64,207584,3859,0,0,0.000000,0.088178,1.000000e+00,0.082017,0.044100,0.07610,0.111800,2.489319e-01,-0.072575,5614,0,"[0.0, 0.1091, 0.0818, 0.0545, 0.0727, 0.08, 0....","[17270, 326, 317, 312, 295, 275, 273, 272, 265...","[0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
BASEMENTAREA_MODE,float64,207584,3936,0,0,0.000000,0.087750,1.000000e+00,0.084076,0.041000,0.07490,0.112700,2.525385e-01,-0.077039,5722,0,"[0.0, 0.0566, 0.0849, 0.1132, 0.083, 0.0642, 0...","[19156, 310, 304, 299, 286, 282, 278, 263, 263...","[0.05, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
CNT_CHILDREN,int64,0,16,0,0,0.000000,0.414316,2.000000e+01,0.720378,0.000000,0.00000,1.000000,1.826257e+00,-0.997626,35576,0,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 14]","[250056, 70623, 30698, 4252, 478, 96, 24, 8, 5...","[0.7, 0.2, 0.09, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0..."
CNT_FAM_MEMBERS,float64,2,18,0,0,1.000000,2.151858,2.100000e+01,0.907937,2.000000,2.00000,3.000000,3.931416e+00,0.372301,32970,0,"[2.0, 1.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, ...","[184411, 78098, 60774, 28387, 3990, 451, 93, 2...","[0.52, 0.22, 0.17, 0.08, 0.01, 0.0, 0.0, 0.0, ..."
CODE_GENDER,object,0,3,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32970,0,"['F', 'M', 'XNA']","[235126, 121125, 4]","[0.66, 0.34, 0.0]"
COMMONAREA_AVG,float64,248360,3299,0,0,0.000000,0.045045,1.000000e+00,0.077045,0.007900,0.02130,0.051900,1.960531e-01,-0.105963,3816,0,"[0.0, 0.0079, 0.0078, 0.008, 0.0077, 0.0086, 0...","[9815, 633, 559, 515, 487, 429, 400, 399, 365,...","[0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
COMMONAREA_MEDI,float64,248360,3318,0,0,0.000000,0.044994,1.000000e+00,0.077140,0.007900,0.02100,0.051800,1.961881e-01,-0.106199,3876,0,"[0.0, 0.0079, 0.008, 0.0078, 0.0014, 0.0086, 0...","[10116, 675, 571, 551, 436, 430, 390, 383, 367...","[0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
COMMONAREA_MODE,float64,248360,3244,0,0,0.000000,0.042930,1.000000e+00,0.075437,0.007300,0.01920,0.049300,1.907862e-01,-0.104925,3836,0,"[0.0, 0.008, 0.0079, 0.0078, 0.0081, 0.0087, 0...","[11294, 633, 629, 599, 481, 467, 461, 420, 402...","[0.03, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
DAYS_BIRTH,int64,0,589,0,0,-840.000000,-534.224968,-2.440000e+02,145.295124,-655.000000,-525.00000,-414.000000,-2.494465e+02,-819.003412,3,2425,"[-470, -492, -477, -518, -454, -479, -458, -47...","[901, 890, 886, 884, 883, 883, 880, 878, 877, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
DAYS_EMPLOYED,float64,64648,559,0,0,-597.000000,-79.405542,0.000000e+00,77.816847,-106.000000,-55.00000,-26.000000,7.311548e+01,-231.926562,0,16536,"[-7.0, -6.0, -4.0, -8.0, -12.0, -13.0, -5.0, -...","[4067, 4061, 3587, 3485, 3354, 3315, 3245, 316...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
DAYS_ID_PUBLISH,int64,0,215,0,0,-239.000000,-99.586905,0.000000e+00,50.596579,-143.000000,-108.00000,-57.000000,-4.176112e-01,-198.756200,2018,694,"[-142, -143, -141, -140, -139, -138, -145, -13...","[4361, 4275, 4239, 4213, 4135, 4109, 4098, 401...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
DAYS_LAST_PHONE_CHANGE,float64,57375,143,0,0,-145.000000,-38.388514,-1.000000e+00,26.094382,-57.000000,-33.00000,-16.000000,1.275648e+01,-89.533503,0,12340,"[-11.0, -15.0, -16.0, -10.0, -17.0, -12.0, -9....","[6036, 5911, 5841, 5807, 5797, 5789, 5732, 571...","[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0..."
DAYS_REGISTRATION,int64,0,669,0,0,-822.000000,-165.638150,0.000000e+00,117.563947,-249.000000,-150.00000,-66.000000,6.478719e+01,-396.063485,0,14035,"[0, -2, -1, -24, -12, -4, -6, -3, -10, -13]","[2316, 1645, 1635, 1601, 1578, 1565, 1559, 155...","[0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
DEF_30_CNT_SOCIAL_CIRCLE,float64,1050,10,0,0,0.000000,0.143452,3.400000e+01,0.456579,0.000000,0.00000,0.000000,1.038347e+00,-0.751442,7915,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 34.0, 7.0,...","[314519, 32771, 6157, 1381, 293, 64, 14, 4, 1, 1]","[0.88, 0.09, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0, 0...."
DEF_60_CNT_SOCIAL_CIRCLE,float64,1050,9,0,0,0.000000,0.100198,2.400000e+01,0.368259,0.000000,0.00000,0.000000,8.219858e-01,-0.621589,29870,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 24.0, 6.0, 7.0]","[325335, 25325, 3666, 695, 152, 24, 4, 3, 1]","[0.91, 0.07, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
ELEVATORS_AVG,float64,189080,272,0,0,0.000000,0.079819,1.000000e+00,0.135249,0.000000,0.00000,0.120000,3.449066e-01,-0.185269,8841,0,"[0.0, 0.08, 0.16, 0.24, 0.12, 0.04, 0.2, 0.32,...","[99185, 11568, 10392, 7138, 6515, 5344, 4770, ...","[0.28, 0.03, 0.03, 0.02, 0.02, 0.02, 0.01, 0.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NONLIVINGAPARTMENTS_MEDI,float64,246861,232,0,0,0.000000,0.008697,1.000000e+00,0.047519,0.000000,0.00000,0.003900,1.018336e-01,-0.084439,1119,0,"[0.0, 0.0039, 0.0078, 0.0116, 0.0155, 0.0194, ...","[65214, 16467, 7547, 4380, 3040, 1959, 1494, 1...","[0.18, 0.05, 0.02, 0.01, 0.01, 0.01, 0.0, 0.0,..."
NONLIVINGAPARTMENTS_MODE,float64,246861,180,0,0,0.000000,0.008116,1.000000e+00,0.046330,0.000000,0.00000,0.003900,9.892270e-02,-0.082691,1071,0,"[0.0, 0.0039, 0.0078, 0.0117, 0.0156, 0.0195, ...","[68893, 16439, 7452, 4247, 2957, 1913, 1392, 9...","[0.19, 0.05, 0.02, 0.01, 0.01, 0.01, 0.0, 0.0,..."
NONLIVINGAREA_AVG,float64,195766,3429,0,0,0.000000,0.028503,1.000000e+00,0.069880,0.000000,0.00360,0.027800,1.654679e-01,-0.108462,5258,0,"[0.0, 0.0012, 0.0044, 0.0022, 0.0031, 0.001, 0...","[68204, 648, 525, 510, 486, 477, 470, 468, 461...","[0.19, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
NONLIVINGAREA_MEDI,float64,195766,3450,0,0,0.000000,0.028386,1.000000e+00,0.070574,0.000000,0.00310,0.026800,1.667105e-01,-0.109939,5281,0,"[0.0, 0.0012, 0.0022, 0.0037, 0.0044, 0.0043, ...","[70821, 636, 547, 531, 493, 483, 482, 479, 471...","[0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
NONLIVINGAREA_MODE,float64,195766,3462,0,0,0.000000,0.027183,1.000000e+00,0.070723,0.000000,0.00110,0.023200,1.657996e-01,-0.111433,5407,0,"[0.0, 0.0011, 0.0046, 0.0033, 0.0012, 0.0023, ...","[78048, 576, 529, 497, 497, 488, 483, 430, 426...","[0.22, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,..."
OBS_30_CNT_SOCIAL_CIRCLE,float64,1050,36,0,0,0.000000,1.425729,3.540000e+02,2.599914,0.000000,0.00000,2.000000,6.521560e+00,-3.670102,15720,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, ...","[189935, 56548, 34559, 23591, 16345, 11020, 74...","[0.53, 0.16, 0.1, 0.07, 0.05, 0.03, 0.02, 0.01..."
OBS_60_CNT_SOCIAL_CIRCLE,float64,1050,35,0,0,0.000000,1.409468,3.510000e+02,2.577724,0.000000,0.00000,2.000000,6.461807e+00,-3.642871,15382,0,"[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, ...","[190806, 56611, 34501, 23477, 16145, 10904, 73...","[0.54, 0.16, 0.1, 0.07, 0.05, 0.03, 0.02, 0.01..."
OCCUPATION_TYPE,object,111996,18,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15382,0,"['Laborers', 'Sales staff', 'Core staff', 'Man...","[63841, 37174, 31931, 24945, 21376, 13234, 114...","[0.18, 0.1, 0.09, 0.07, 0.06, 0.04, 0.03, 0.03..."
ORGANIZATION_TYPE,object,0,58,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15382,0,"['Business Entity Type 3', 'XNA', 'Self-employ...","[78832, 64648, 44332, 19390, 12909, 12032, 119...","[0.22, 0.18, 0.12, 0.05, 0.04, 0.03, 0.03, 0.0..."
OWN_CAR_AGE,float64,235241,63,0,0,0.000000,12.023741,9.100000e+01,11.880848,5.000000,9.00000,15.000000,3.531020e+01,-11.262721,4531,0,"[7.0, 3.0, 8.0, 4.0, 6.0, 2.0, 1.0, 9.0, 10.0,...","[8625, 7397, 6984, 6909, 6880, 6832, 5930, 586...","[0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.0..."
REGION_POPULATION_RELATIVE,float64,0,92,0,0,0.000253,0.020917,7.250800e-02,0.013915,0.010006,0.01885,0.028663,4.819040e-02,-0.006356,9977,0,"[0.035792000000000004, 0.04622, 0.030755, 0.02...","[18990, 15939, 14154, 13549, 12916, 12897, 116...","[0.05, 0.04, 0.04, 0.04, 0.04, 0.04, 0.03, 0.0..."
REGION_RATING_CLIENT,int64,0,3,0,0,1.000000,2.050506,3.000000e+00,0.510947,2.000000,2.00000,2.000000,3.051963e+00,1.049049,0,37961,"[2, 3, 1]","[262340, 55954, 37961]","[0.74, 0.16, 0.11]"
REGION_RATING_CLIENT_W_CITY,int64,0,4,0,0,-1.000000,2.028932,3.000000e+00,0.504586,2.000000,2.00000,2.000000,3.017920e+00,1.039943,0,40343,"[2, 3, 1, -1]","[265260, 50652, 40342, 1]","[0.74, 0.14, 0.11, 0.0]"
REG_CITY_NOT_LIVE_CITY,int64,0,2,0,0,0.000000,0.078076,1.000000e+00,0.268292,0.000000,0.00000,0.000000,6.039278e-01,-0.447776,27815,0,"[0, 1]","[328440, 27815]","[0.92, 0.08]"
REG_CITY_NOT_WORK_CITY,int64,0,2,0,0,0.000000,0.229661,1.000000e+00,0.420616,0.000000,0.00000,0.000000,1.054068e+00,-0.594745,0,0,"[0, 1]","[274437, 81818]","[0.77, 0.23]"
REG_REGION_NOT_LIVE_REGION,int64,0,2,0,0,0.000000,0.015649,1.000000e+00,0.124113,0.000000,0.00000,0.000000,2.589106e-01,-0.227613,5575,0,"[0, 1]","[350680, 5575]","[0.98, 0.02]"
REG_REGION_NOT_WORK_REGION,int64,0,2,0,0,0.000000,0.051371,1.000000e+00,0.220753,0.000000,0.00000,0.000000,4.840456e-01,-0.381305,18301,0,"[0, 1]","[337954, 18301]","[0.95, 0.05]"
TARGET,int64,0,3,0,0,-1.000000,-0.067140,1.000000e+00,0.449443,0.000000,0.00000,0.000000,8.137689e-01,-0.948049,24825,48744,"[0, -1, 1]","[282686, 48744, 24825]","[0.79, 0.14, 0.07]"
TOTALAREA_MODE,float64,171055,5252,0,0,0.000000,0.103193,1.000000e+00,0.108041,0.041500,0.06900,0.128700,3.149527e-01,-0.108567,8975,0,"[0.0, 0.057, 0.0551, 0.0548, 0.055, 0.0555, 0....","[655, 285, 268, 265, 263, 259, 258, 255, 254, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
WALLSMATERIAL_MODE,object,180234,7,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8975,0,"['Panel', 'Stone, brick', 'Block', 'Wooden', '...","[77309, 75249, 10681, 6156, 2649, 2068, 1909]","[0.22, 0.21, 0.03, 0.02, 0.01, 0.01, 0.01]"
WEEKDAY_APPR_PROCESS_START,object,0,7,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8975,0,"['TUESDAY', 'WEDNESDAY', 'MONDAY', 'THURSDAY',...","[63652, 60391, 59120, 59009, 57588, 38455, 18040]","[0.18, 0.17, 0.17, 0.17, 0.16, 0.11, 0.05]"
YEARS_BEGINEXPLUATATION_AVG,float64,172863,298,0,0,0.000000,0.977889,1.000000e+00,0.057929,0.976700,0.98160,0.986600,1.091430e+00,0.864348,0,777,"[0.9871, 0.9856, 0.9866, 0.9861, 0.9801, 0.980...","[5012, 4866, 4861, 4841, 4788, 4777, 4763, 464...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
YEARS_BEGINEXPLUATATION_MEDI,float64,172863,255,0,0,0.000000,0.977903,1.000000e+00,0.058562,0.976700,0.98160,0.986600,1.092685e+00,0.863121,0,733,"[0.9871, 0.9861, 0.9856, 0.9866, 0.9801, 0.980...","[5028, 4918, 4884, 4871, 4773, 4729, 4693, 460...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
YEARS_BEGINEXPLUATATION_MODE,float64,172863,229,0,0,0.000000,0.977239,1.000000e+00,0.063165,0.976700,0.98160,0.986600,1.101042e+00,0.853435,0,764,"[0.9871, 0.9866, 0.9861, 0.9801, 0.9856, 0.980...","[5011, 4902, 4842, 4779, 4742, 4723, 4659, 461...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
YEARS_BUILD_AVG,float64,236306,152,0,0,0.000000,0.752283,1.000000e+00,0.113267,0.687200,0.75520,0.823200,9.742874e-01,0.530279,2426,3168,"[0.8232, 0.8164, 0.8028, 0.728, 0.7348, 0.8096...","[3506, 3361, 3293, 3228, 3213, 3212, 3186, 315...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
YEARS_BUILD_MEDI,float64,236306,151,0,0,0.000000,0.755548,1.000000e+00,0.112057,0.691400,0.75850,0.825600,9.751805e-01,0.535916,2478,3165,"[0.8256, 0.8189, 0.8054, 0.8121, 0.7316, 0.738...","[3510, 3370, 3284, 3249, 3224, 3172, 3162, 314...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
YEARS_BUILD_MODE,float64,236306,155,0,0,0.000000,0.759452,1.000000e+00,0.110112,0.699400,0.76480,0.823600,9.752727e-01,0.543632,2444,3359,"[0.8301, 0.8236, 0.8171, 0.7387, 0.8105, 0.745...","[3478, 3362, 3226, 3211, 3186, 3170, 3131, 313...","[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.0..."
is_test,int64,0,2,0,0,0.000000,0.136823,1.000000e+00,0.343661,0.000000,0.00000,0.000000,8.103994e-01,-0.536753,48744,0,"[0, 1]","[307511, 48744]","[0.86, 0.14]"
is_train,int64,0,2,0,0,0.000000,0.863177,1.000000e+00,0.343661,1.000000,1.00000,1.000000,1.536753e+00,0.189601,0,48744,"[1, 0]","[307511, 48744]","[0.86, 0.14]"
valid_no,float64,0,5,0,0,-1.000000,2.021108,4.000000e+00,1.589254,1.000000,2.00000,3.000000,5.136047e+00,-1.093830,0,0,"[1.0, 2.0, 3.0, 4.0, -1.0]","[76879, 76878, 76877, 76877, 48744]","[0.22, 0.22, 0.22, 0.22, 0.14]"

#==============================================================================
# SUCCESS !!! /mnt/c/Users/gixo/go/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py
#==============================================================================

time: 0.27min